{% set version = "2.15.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-learnbayes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/LearnBayes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/LearnBayes/LearnBayes_{{ version }}.tar.gz
  sha256: 7ae3458c64b426b7a753bf0613dc1e6eebccddcadbea9e86687ab2312861d192

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-coda
    - r-lattice
    - r-survival
  run:
    - r-base
    - r-coda
    - r-lattice
    - r-survival

test:
  commands:
    - $R -e "library('LearnBayes')"           # [not win]
    - "\"%R%\" -e \"library('LearnBayes')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=LearnBayes
  license: GPL-2.0-or-later
  summary: A collection of functions helpful in learning the basic tenets of Bayesian statistical inference.  It contains functions for summarizing basic one and two parameter posterior distributions and predictive distributions.  It contains MCMC algorithms for summarizing posterior distributions defined by the user.  
    It also contains functions for regression models, hierarchical models, Bayesian tests, and illustrations of Gibbs sampling.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
