{% set version = "2.15.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-learnbayes
  version: {{ version|replace("-", "_") }}

source:
  fn: LearnBayes_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/LearnBayes_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/LearnBayes/LearnBayes_{{ version }}.tar.gz
  sha256: 9b110858456523ca0b2a63f22013c4e1fbda6674b9d84dc1f4de8bffc5260532

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('LearnBayes')"  # [not win]
    - "\"%R%\" -e \"library('LearnBayes')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=LearnBayes
  license: GPL (>= 2)
  summary: LearnBayes contains a collection of functions helpful in learning the basic tenets
    of Bayesian statistical inference.  It contains functions for summarizing basic
    one and two parameter posterior distributions and predictive distributions.  It
    contains MCMC algorithms for summarizing posterior distributions defined by the
    user.  It also contains functions for regression models, hierarchical models, Bayesian
    tests, and illustrations of Gibbs sampling.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
